spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true

management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,db
