spring:
  config:
    activate:
      on-profile: local
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

logging:
  level:
    root: INFO
    com.agenttavern: INFO
