import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

async function create(page: Page, spectator = false) {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '今夜，和谁过招？' })).toBeVisible()
  if (spectator) await page.getByRole('button', { name: 'AI 决策剧场', exact: true }).click()
  await page.getByRole('button', { name: '落座，开局 →' }).click()
  await expect(page.getByRole('region', { name: '扑克牌桌' })).toBeVisible()
  if (!spectator) await expect(page.getByRole('button', { name: '全下', exact: true })).toBeEnabled()
}

test('player chat reaches a second window, survives reload, and appears in replay', async ({ page, context }) => {
  await create(page)
  const before = await (await page.request.get('/api/tables/current')).json()
  const second = await context.newPage()
  await second.goto('/')
  await expect(second.getByRole('region', { name: '扑克牌桌' })).toBeVisible()
  await page.getByRole('textbox', { name: '牌桌发言' }).fill('浏览器验收：今晚慢慢喝茶。')
  await page.getByRole('button', { name: '发送到牌桌 ↗' }).click()
  await expect(second.locator('.agent-speech')).toContainText('今晚慢慢喝茶')
  await page.reload()
  await expect(page.locator('.agent-speech')).toContainText('今晚慢慢喝茶')
  expect((await (await page.request.get('/api/tables/current')).json()).tableId).toBe(before.tableId)
  // Exact action is chosen by the server's current legal range.
  await page.getByRole('button', { name: /FOLD · F/ }).click()
  await expect.poll(async () => (await (await page.request.get('/api/tables/current')).json()).version).toBeGreaterThan(before.version)
  await page.getByRole('button', { name: '牌局回放', exact: true }).click()
  await expect(page.getByRole('slider', { name: '回放时间轴' })).toBeVisible()
  await page.getByRole('button', { name: '下一步', exact: true }).click()
  await expect(page.getByRole('button', { name: '上一步', exact: true })).toBeEnabled()
  const replay = await (await page.request.get(`/api/tables/current/replay?tableId=${before.tableId}&after=0`)).json()
  expect(replay.frames.every((frame: { holeCards: unknown[]; seats: object[] }) => frame.holeCards.length <= 2 && frame.seats.every(seat => !('holeCards' in seat)))).toBe(true)
  expect(replay.frames.some((frame: { chat: { text: string }[] }) => frame.chat.some(chat => chat.text.includes('今晚慢慢喝茶')))).toBe(true)
})

test('spectator steps and autoplay update through SSE while the log stays inside the viewport', async ({ page }) => {
  await create(page, true)
  const before = await (await page.request.get('/api/tables/current')).json()
  expect(before.holeCards).toEqual([])
  await page.getByRole('button', { name: '推进一步', exact: true }).click()
  await expect(page.getByRole('button', { name: '推进一步', exact: true })).toBeEnabled()
  await expect.poll(async () => (await (await page.request.get('/api/tables/current')).json()).version).toBe(before.version + 1)
  await page.getByLabel('观战速度').selectOption('4')
  await page.getByRole('button', { name: '自动播放', exact: true }).click()
  await expect.poll(async () => (await (await page.request.get('/api/tables/current')).json()).version).toBeGreaterThan(before.version + 15)
  await page.getByRole('button', { name: '暂停', exact: true }).click()
  const dock = await page.locator('.action-dock').boundingBox()
  expect(dock!.y + dock!.height).toBeLessThanOrEqual(900)
  expect(await page.locator('.log-item').count()).toBeGreaterThan(10)
  await expect(page.locator('.hero-cards')).toHaveCount(0)
})

test('a dropped connection catches up, and an expired cookie returns to the lobby', async ({ page, context }) => {
  await create(page, true)
  const original = await (await page.request.get('/api/tables/current')).json()
  await context.setOffline(true)
  await expect(page.getByRole('alert')).toContainText('连接中断')
  await context.setOffline(false)
  await expect(page.getByRole('button', { name: '推进一步', exact: true })).toBeEnabled()
  expect((await (await page.request.get('/api/tables/current')).json()).tableId).toBe(original.tableId)
  await context.setOffline(true)
  await expect(page.getByRole('alert')).toContainText('连接中断')
  await context.clearCookies()
  await context.setOffline(false)
  await expect(page.getByRole('heading', { name: '今夜，和谁过招？' })).toBeVisible()
})

test('mobile controls fit, and keyboard typing never folds the player', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await create(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: '动态', exact: true }).click()
  const version = (await (await page.request.get('/api/tables/current')).json()).version
  await page.getByRole('textbox', { name: '牌桌发言' }).pressSequentially('fcr')
  expect((await (await page.request.get('/api/tables/current')).json()).version).toBe(version)
  await page.getByRole('button', { name: '关闭牌桌动态' }).click()
  const box = await page.getByRole('button', { name: '全下', exact: true }).boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: 'test-results/mobile-table.png', fullPage: true })
})

test('sound settings unlock, mute and preserve reduced motion on mobile', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.getByText('声效',{exact:true}).click()
  await page.getByRole('button',{name:'开启音效',exact:true}).click()
  await expect(page.getByRole('button',{name:'静音',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button',{name:'静音',exact:true}).click()
  await page.getByRole('checkbox',{name:'减少动态效果'}).check()
  await page.getByRole('slider',{name:'音效音量'}).fill('25')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([])
  await page.reload()
  await page.getByText('声效',{exact:true}).click()
  await expect(page.getByRole('button',{name:'开启音效',exact:true})).toBeVisible()
  await expect(page.getByRole('checkbox',{name:'减少动态效果'})).toBeChecked()
  await expect(page.getByRole('slider',{name:'音效音量'})).toHaveValue('25')
})

test('anonymous local career survives reload and requires confirmation to clear', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(()=>localStorage.setItem('agent-tavern.career.v1',JSON.stringify({games:2,wins:1,hands:8,netChips:3000,biggestPot:4200,actions:{FOLD:2,CHECK:1,CALL:4,RAISE:2,ALL_IN:0},opponents:{},cursors:{},completedTables:[],tablePots:{}})))
  await page.reload()
  await page.getByRole('button',{name:'本地战绩'}).click()
  await expect(page.getByRole('heading',{name:'我的茶馆战绩'})).toBeVisible()
  await expect(page.getByText('50%')).toBeVisible();await expect(page.getByText('+3,000')).toBeVisible()
  await page.getByRole('button',{name:'清除本地战绩'}).click()
  await expect(page.getByText('此操作无法撤销。')).toBeVisible()
  await page.getByRole('button',{name:'确认清除'}).click()
  await expect(page.getByText('0%',{exact:true})).toBeVisible()
  await page.reload();await page.getByRole('button',{name:'本地战绩'}).click()
  await expect(page.getByText('0%',{exact:true})).toBeVisible()
})

test('lobby and table meet automated WCAG A/AA checks', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: '落座，开局 →' })).toBeEnabled()
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()).violations).toEqual([])
  await page.getByRole('button', { name: '落座，开局 →' }).click()
  await expect(page.getByRole('button', { name: '全下', exact: true })).toBeEnabled()
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()).violations).toEqual([])
  await page.screenshot({ path: 'test-results/desktop-table.png' })
})
